import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  unlinkSync,
  writeFileSync
} from 'node:fs'
import { basename, relative, resolve } from 'node:path'

import { FILM, SCENES } from '../scenes.mjs'
import {
  PROJECT,
  REPORTS_DIR,
  ensureDirs,
  readJson,
  writeJson
} from './lib/project.mjs'
import {
  displayCaption,
  parseCaptions,
  serializeCaptions
} from './lib/speech.mjs'
import { buildTimeline } from './lib/timeline.mjs'
import {
  renderIndex,
  renderMotionSidecar,
  renderScript,
  renderStoryboard,
  renderSubcomposition
} from './lib/render-scene.mjs'

ensureDirs()
const timeline = buildTimeline()
if (timeline.duration < FILM.minimumDurationSeconds)
  throw new Error(`Projected reel is ${timeline.duration.toFixed(2)}s; at least ${FILM.minimumDurationSeconds}s is required`)

writeFileSync(resolve(PROJECT, 'STORYBOARD.md'), renderStoryboard(timeline))
writeFileSync(resolve(PROJECT, 'SCRIPT.md'), renderScript(timeline))

if (process.argv.includes('--story-only')) {
  console.log(`Story files ready: ${timeline.duration.toFixed(2)}s projected`)
  process.exit(0)
}

const compositions = resolve(PROJECT, 'compositions')
mkdirSync(compositions, { recursive: true })
const expected = new Set(SCENES.flatMap(scene => [`${scene.id}.html`, `${scene.id}.motion.json`]))
for (const file of readdirSync(compositions)) {
  const path = resolve(compositions, file)
  if (expected.has(file) || !file.endsWith('.html')) continue
  if (readFileSync(path, 'utf8').startsWith('<!-- generated by scripts/build.mjs'))
    unlinkSync(path)
}

for (const scene of SCENES) {
  const timelineScene = timeline.scenes.find(item => item.id === scene.id)
  writeFileSync(
    resolve(compositions, `${scene.id}.html`),
    renderSubcomposition(scene, timelineScene)
  )
  writeJson(
    resolve(compositions, `${scene.id}.motion.json`),
    renderMotionSidecar(scene, timelineScene)
  )
}

writeFileSync(resolve(PROJECT, 'index.html'), renderIndex(timeline))
writeJson(resolve(REPORTS_DIR, 'timeline.json'), {
  ...timeline,
  scenes: timeline.scenes.map(scene => ({
    ...scene,
    audio: scene.audio ? relative(PROJECT, scene.audio) : null,
    captions: scene.captions ? relative(PROJECT, scene.captions) : null
  }))
})

const captionSets = timeline.scenes.every(scene => scene.captions && existsSync(scene.captions))
if (captionSets) {
  const captions = timeline.scenes.flatMap(scene =>
    parseCaptions(readFileSync(scene.captions, 'utf8')).map(caption => ({
      ...caption,
      start: caption.start + scene.audioStart,
      end: caption.end + scene.audioStart,
      text: displayCaption(caption.text)
    }))
  )
  writeFileSync(resolve(REPORTS_DIR, `${FILM.id}.srt`), serializeCaptions(captions))
  writeFileSync(resolve(REPORTS_DIR, 'chapters.ffmetadata'), [
    ';FFMETADATA1',
    `title=${FILM.title}`,
    `comment=${FILM.chaptersComment}`,
    ...timeline.scenes.flatMap(scene => [
      '[CHAPTER]',
      'TIMEBASE=1/1000',
      `START=${Math.round(scene.start * 1000)}`,
      `END=${Math.round(scene.end * 1000)}`,
      `title=${scene.chapter}`
    ])
  ].join('\n'))
}

console.log(
  `${SCENES.length} scenes built · ${timeline.duration.toFixed(2)}s · ` +
  `${captionSets ? 'captions ready' : 'no generated narration yet'}`
)
console.log(`Entry composition: ${basename(resolve(PROJECT, 'index.html'))}`)
